@startuml sdvxest

entity User {
  id: number (pk)
  --
  settingId: number (fk)
  username: string
  password: string
  playerId: string
  playerName: string
  volforce: float
  arenaRank: number(enum)
  ultimateScore: number
  deleted: boolean
  createdAt: date
  updatedAt: date
  deletedAt: date
  isAdmin: boolean
}
' (op)rivalData

entity Song {
  id: number (pk)
  --
  name: string
  artist: string
  version: number
  level: number
  difficult: number(enum)
  maxExScore: number
  createdAt: date
  updatedAt: date
}
' (op) bpm(min - max)

entity ExScore {
  id: number (pk)
  --
  userId: number (fk)
  songId: number (fk)
  exScore: number
  playCount: number
  createdAt: date
  updatedAt: date
}

' アップロード状況
entity UploadStatus {
  id: number (pk)
  --
  userId: number (fk)
  uploadScoreCount: number
  createdAt: date
  updatedAt: date
}

' 差分
entity ExScoreDifference {
  id: number (pk)
  --
  userId: number (fk)
  songId: number (fk)
  uploadStatusId: number (fk)
  beforeExScore: number
  afterExScore: number
  createdAt: date
  updatedAt: date
}

' 公開設定
entity Setting {
  id: number (pk)
  --
  opened: number (enum)
}

Setting ---- User
User --o{ UploadStatus
User --o{ ExScore

Song --o{ ExScore
Song --o{ ExScoreDifference

UploadStatus --o{ ExScoreDifference

@enduml